INSERT INTO MEMBER (ID, MEMBER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'zumgu', 'test', '줌구', 'wckhg89@gmail.com');

INSERT INTO CONTENT (ID, CONTENT, CREATED_AT, MEMBER_FK_ID) VALUES (1, '테스트1글 입니다.', CURRENT_TIMESTAMP(), 1);
INSERT INTO CONTENT (ID, CONTENT, CREATED_AT, MEMBER_FK_ID) VALUES (2, '테스트2글 입니다.', CURRENT_TIMESTAMP(), 1);
INSERT INTO CONTENT (ID, CONTENT, CREATED_AT, MEMBER_FK_ID) VALUES (3, '테스트3글 입니다.', CURRENT_TIMESTAMP(), 1);
INSERT INTO CONTENT (ID, CONTENT, CREATED_AT, MEMBER_FK_ID) VALUES (4, '테스트4글 입니다.', CURRENT_TIMESTAMP(), 1);
INSERT INTO CONTENT (ID, CONTENT, CREATED_AT, MEMBER_FK_ID) VALUES (5, '테스트5글 입니다.', CURRENT_TIMESTAMP(), 1);

